### ISSUE TITLE
Client hard coded

### ISSUE THREAD

**Issue by matthew-inamdar** [bastones/currencyconvertor#1]
https://github.com/bastones/currencyconvertor/blob/23b9903fe68b2384d4e24c6ab723e6349ed3c291/app/Support/FloatRatesCurrencyConversion.php#L128

Would recommend using DI to inject the client dependency in the constructor. Since the class itself is resolved by the container, this dependency should also be resolved.

**Comment by bastones** [comment]
The `Client` class is only required if the currencies to convert between differ and where the exchange rate information for that currency is not already present in the cache. By instantiating the class within the constructor, we would be making the instance unnecessarily available across the entire class when it is only required within the `getExchangeRate()` method when the conditions described above are met.

In light of this, the only possible benefit I can see from doing this is to decouple the project away from the Guzzle library using dependency injection to resolve an implementing class (such as Guzzle). However this would require us to have a middle layer for each library we support, as it is pointless using dependency injection unless we can guarantee the methods we call to make an HTTP request remain the same across any implementing class the container might resolve.
